AWSTemplateFormatVersion: 2010-09-09

Parameters:

  GitHubOwner:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: main

  CodestarConnectionArn:
    Type: String

Resources:

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-infrastructure-artifacts"
  
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
            
      Policies:
        - PolicyName: CodeBuildCloudformationAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactStoreBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactStoreBucket}/*"

              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                Resource: "*"


  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Infrastructure-codepipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactStoreBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactStoreBucket}/*"

              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Ref CodestarConnectionArn

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:StopBuild
                Resource: "*"

  DevBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DevBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: ci/dev-buildspec.yml
      TimeoutInMinutes: 10

  StagingBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: StagingBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: ci/staging-buildspec.yml
      TimeoutInMinutes: 10

  ProdBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ProdBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: ci/prod-buildspec.yml
      TimeoutInMinutes: 10


  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "Infrastructure-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreBucket

      Stages:
      
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodestarConnectionArn
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
                BranchName: !Ref GitHubBranch
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceOutput

        - Name: DevApproval
          Actions:
            - Name: DevApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
        

        - Name: Dev-Build
          Actions:
            - Name: DevBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DevOutput
              Configuration:
                ProjectName: !Ref DevBuildProject

        - Name: StagingApproval
          Actions:
            - Name: StagingApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
        
        - Name: Staging-Build
          Actions:
            - Name: StagingBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: StageOutput
              Configuration:
                ProjectName: !Ref StagingBuildProject

        - Name: ProdApproval
          Actions:
            - Name: ProdApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
                
        - Name: Prod-Build
          Actions:
            - Name: ProdBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: ProdOutput
              Configuration:
                ProjectName: !Ref ProdBuildProject
