version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting build process..."

  pre_build:
    commands:
      - aws cloudformation describe-stacks --stack-name Staging-ServerlessWebApp --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text
      - DIST_ID=$(aws cloudformation describe-stacks --stack-name Staging-ServerlessWebApp --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
  build:
    commands:
      - echo "Uploading files to S3..."
      - aws s3 sync app/ s3://staging-s3-bucketsite/
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"

artifacts:
  files:
    - '**/*'

